name: .NET CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CI_USER_COUNT: 1000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --filter "Category!=Performance"
        # retirer "--filter "Category=Performance" pour exécuter les tests de performance sur 1000 users
      - name: Publish application
        run: dotnet publish Api/TourGuide.csproj -c Release -o publish

      - name: Create ZIP archive
        run: zip -r tourguide-release.zip publish

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tourguide-build
          path: tourguide-release.zip